apiVersion: apps/v1
kind: Deployment
metadata:
  name: gist-deployment
  labels:
    app: gist-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gist-deployment
  template:
    metadata:
      labels:
        app: gist-deployment
    spec:
      containers:
        - name: gist-deployment
          image: gist-kub-workshop:1.0
          ports:
            - containerPort: 8080